# 5K Image Quality Requirements

resolution:
  width: 5120
  height: 2880
  min_megapixels: 14.7

color:
  bit_depth: 24  # RGB color space
  color_space: "RGB"
  dynamic_range:
    min: 220
    max: 255

quality:
  dpi: 300
  min_sharpness: 70
  max_noise_level: 120
  compression_quality: 95
  min_file_size_mb: 1.5

enhancement:
  upscale_method: "lanczos"
  denoise_strength: 0.5  # Reduced for better detail preservation
  sharpening:
    radius: 1.0
    amount: 1.3
    threshold: 0.0
  color_enhancement:
    saturation: 1.2
    contrast: 1.15
    brightness: 1.1  # Increased to prevent dark output
    white_balance: true
  detail_enhancement:
    strength: 1.3
    edge_preservation: 0.8
    noise_reduction: 0.5
    local_contrast: 1.2
    multi_scale_levels: 3
    adaptive_sharpening: true

processing:
  batch_size: 1024
  memory_limit_mb: 4096
  use_gpu: false  # Set to true if GPU is available
  precision: "float32"
  threads: 4

output:
  format: "PNG"
  compression_level: 6  # 0-9, lower is less compression
  metadata_preserve: true
  color_profile: "sRGB"
