# 5K Image Quality Requirements

resolution:
  width: 5120
  height: 2880
  min_megapixels: 14.7

color:
  bit_depth: 24  # RGB color space
  color_space: "RGB"
  dynamic_range:
    min: 220
    max: 255

quality:
  dpi: 300
  min_sharpness: 70
  max_noise_level: 120  # Adjusted based on typical enhanced image characteristics
  compression_quality: 95
  min_file_size_mb: 1.5

enhancement:
  upscale_method: "bicubic"
  denoise_strength: 0.7
  sharpening:
    radius: 1.0
    amount: 1.5
    threshold: 0.0
  color_enhancement:
    saturation: 1.1
    contrast: 1.1
    brightness: 1.0
