# Distributed Processing Configuration

# Cluster Configuration
cluster:
  nodes: 4
  memory_per_node: "16GB"
  cpu_per_node: "8 cores"
  gpu_per_node: "1"
  network:
    interface: "eth0"
    bandwidth: "10Gbps"
  storage:
    shared_path: "/shared"
    type: "nfs"

# Task Distribution Configuration
tasks:
  image_processing:
    mode: "distributed"
    batch_size: 16
    priority: 1
    timeout: 300  # seconds
    
  model_inference:
    mode: "parallel"
    batch_size: 8
    priority: 2
    timeout: 180  # seconds
    
  quality_validation:
    mode: "parallel"
    batch_size: 32
    priority: 3
    timeout: 120  # seconds

# Resource Management
resource_management:
  scheduling:
    algorithm: "fair_share"
    preemption: true
    max_retries: 3
  
  memory:
    allocation_strategy: "dynamic"
    swap_threshold: "90%"
    minimum_free: "2GB"
  
  gpu:
    sharing_strategy: "exclusive"
    memory_buffer: "1GB"
    compute_mode: "default"

# Fault Tolerance
fault_tolerance:
  heartbeat_interval: 10  # seconds
  node_timeout: 30  # seconds
  recovery:
    strategy: "checkpoint"
    interval: 300  # seconds
    storage: "/shared/checkpoints"

# Performance Monitoring
monitoring:
  metrics:
    - cpu_usage
    - memory_usage
    - gpu_usage
    - network_io
    - task_throughput
  interval: 15  # seconds
  retention: "7d"
  alerts:
    cpu_threshold: 90
    memory_threshold: 85
    gpu_threshold: 95

# Communication
communication:
  protocol: "grpc"
  ports:
    main: 50051
    monitoring: 50052
    data: 50053
  security:
    encryption: true
    authentication: true
    cert_path: "/etc/certs"

# Logging
logging:
  level: "INFO"
  format: "json"
  output:
    file: "/var/log/distributed.log"
    console: true
  rotation:
    max_size: "100MB"
    max_files: 10

# System Limits
limits:
  max_concurrent_tasks: 100
  max_queue_size: 1000
  max_batch_size: 64
  max_memory_per_task: "4GB"
